INSERT INTO teams (team_abbr, team_name, league, division) VALUES
('BAL', 'Baltimore Orioles', 'AL', 'East'),
('BOS', 'Boston Red Sox', 'AL', 'East'),
('NYY', 'New York Yankees', 'AL', 'East'),
('TBR', 'Tampa Bay Rays', 'AL', 'East'),
('TOR', 'Toronto Blue Jays', 'AL', 'East'),
('CHW', 'Chicago White Sox', 'AL', 'Central'),
('CLE', 'Cleveland Guardians', 'AL', 'Central'),
('DET', 'Detroit Tigers', 'AL', 'Central'),
('KCR', 'Kansas City Royals', 'AL', 'Central'),
('MIN', 'Minnesota Twins', 'AL', 'Central'),
('HOU', 'Houston Astros', 'AL', 'West'),
('LAA', 'Los Angeles Angels', 'AL', 'West'),
('ATH', 'Athletics', 'AL', 'West'),
('SEA', 'Seattle Mariners', 'AL', 'West'),
('TEX', 'Texas Rangers', 'AL', 'West'),
('ATL', 'Atlanta Braves', 'NL', 'East'),
('MIA', 'Miami Marlins', 'NL', 'East'),
('NYM', 'New York Mets', 'NL', 'East'),
('PHI', 'Philadelphia Phillies', 'NL', 'East'),
('WSN', 'Washington Nationals', 'NL', 'East'),
('CHC', 'Chicago Cubs', 'NL', 'Central'),
('CIN', 'Cincinnati Reds', 'NL', 'Central'),
('MIL', 'Milwaukee Brewers', 'NL', 'Central'),
('PIT', 'Pittsburgh Pirates', 'NL', 'Central'),
('STL', 'St. Louis Cardinals', 'NL', 'Central'),
('ARI', 'Arizona Diamondbacks', 'NL', 'West'),
('COL', 'Colorado Rockies', 'NL', 'West'),
('LAD', 'Los Angeles Dodgers', 'NL', 'West'),
('SDP', 'San Diego Padres', 'NL', 'West'),
('SFG', 'San Francisco Giants', 'NL', 'West');
